# Builds and pushes a new version of unstoppabledomains/zilliqa-dev-node image

name: Build & Push Zilliqa Dev Node

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "New tag"
        default: "v0.0.0"
        required: true

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: unstoppabledomains/zilliqa-dev-node:${{ github.event.inputs.tag }}
          context: ./docker/build

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
