# Builds and pushes a new version of unstoppabledomains/zilliqa-dev-node image

name: Build & Push Zilliqa Dev Node

on:
  push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: unstoppabledomains/zilliqa-dev-node:v0.0.1
          # file: ${{ github.workspace }}/docker/build/Dockerfile
          context: ./docker/build
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
